name: C/C++ CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        build_type: [ Debug, Release ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
         submodules: recursive  # 如果有子模块

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -GNinja

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }}